const products = 
    [
	{
		name: "Dalfonna",
		cathegory_main: "Jakker",
		cathegory_under: "Skalljakker",
		age: 1,
		color: ['green', 'purple', 'blue'],
		size: [86, 92, 104],
		quality1: ["vannavstøtende", 'vindtett'],
		price: "255",
		url: ['../images/jackets/dalfonna1.jpg', '../images/jackets/dalfonna2.jpg', '../images/jackets/dalfonna3.jpg', '../images/jackets/dalfonna4'],
		ingress: "Jakken er nydelig på skitur, i akebakken og på vei til barnehagen en kald høstdag",
        description: "",
		id: 0,
		amount: 0 
        
	},
	{
		name: "Dirdalnes",
		cathegory_main: "Jakker",
		cathegory_under: "Fleece",
		age: 2,
		color: ['red'],
		size: [86, 92, 104, 110, 116, 122],
		quality1: ["varm"],
		price: "289",
		url: ['../images/jackets/dirdalnes_fleece1.jpg', '../images/jackets/dirdalnes_fleece2.jpg', '../images/jackets/dirdalnes_fleece3.jpg'],
		ingress: "Perfekt mellomplagg på kalde høstdager.",
        description: "",
		id: 1,
		amount: 0 
	},
	{
		name: "Moltehei",
		cathegory_main: "Jakker",
		cathegory_under: "Skalljakke",
		age: 3,
		color: ['red', 'blue'],
		size: [86, 110, 116, 122],
		quality1: ["vindtett"],
		price: "599",
		url: ['../images/jackets/Moltehei_softshell1.jpg', '../images/jackets/Moltehei_softshell2.jpg', '../images/jackets/Moltehei_softshell4.jpg'],
		ingress: "Denne jakken holder vinden ute når høsten setter inn.",
        description: "",
        id: 2,
		amount: 0 
	},
	{
		name: "Nissedal",
		cathegory_main: "Jakker",
		cathegory_under: "Dunjakke",
		age: 3,
		color: ['red', 'blue'],
		size: [86, 110, 116, 122],
		quality1: ["varm", "vindtett"],
		price: "599",
		url: ['../images/jackets/Nissedal1.jpg', '../images/jackets/Nissedal2.jpg', '../images/jackets/Nissedal3.jpg'],
		ingress: "Varm og god når høst blir til vinter.",
        description: "",
        id: 3,
		amount: 0 
	},
	{
		name: "Vestland",
		cathegory_main: "Jakker",
		cathegory_under: "Regnjakke",
		age: 3,
		color: ['red', 'blue', 'purple'],
		size: [86, 110, 116, 122],
		quality1: ["vindtett", "vanntett"],
		price: "599",
		url: ['../images/jackets/vestland_regnjakke1.jpg', '../images/jackets/vestland_regnjakke2.jpg', '../images/jackets/vestland_regnjakke3.jpg'],
		ingress: "Holder poden tørr når regnet siler ned.",
        description: "",
        id: 4,
		amount: 0 
	},

//------------------------------------------------------------------------------------------
	{
		name: "Krupsili vattert bukse",
		cathegory_main: "Bukser",
		cathegory_under: "Overtrekksbukse",
		age: 2,
		color: ['red', 'black'],
		size: [116, 122],
		quality1: ["vindtett"],
		price: "229",
		url: ['../images/pants/dalfonna_vattert1.jpg', '../images/pants/dalfonna_vattert2.jpg'],
		ingress: "Perfekt overtrekksbukse når gjørma setter inn.",
        description: "",
        id: 5,
		amount: 0 
	},
	{
		name: "Harestua",
		cathegory_main: "Bukser",
		cathegory_under: "Regnbukse",
		age: 2,
		color: ['red', 'gray'],
		size: [86, 116, 122],
		quality1: ["vindtett", 'vanntett', 'strikk'],
		price: "689",
		url: ['../images/pants/harestua_softshell1.jpg', '../images/pants/harestua_softshell2.jpg', '../images/pants/harestua_softshell3'],
		ingress: "Detter ikke av - uansett hvor aktiv ungen er.",
        description: "",
        id: 6,
		amount: 0 
    },
    {
		name: "Fluppilupp",
		cathegory_main: "Bukser",
		cathegory_under: "Overtrekksbukse",
		age: 2,
		color: ['red', 'gray'],
		size: [86, 110, 116, 122],
		quality1: ["vindtett", 'vanntett', 'varm'],
		price: "1299",
		url: ['../images/pants/labbedal_softshell1.jpg', '../images/pants/labbedal_softshell2.jpg', '../images/pants/labbedal_softshell3.jpg'],
		ingress: "Holder ungen varm og tørr - uten at hen merker at den er på.",
        description: "",
        id: 7,
		amount: 0 
    },
    {
		name: "Robust",
		cathegory_main: "Bukser",
		cathegory_under: "Regnbukse",
		age: 2,
		color: ['red', 'gray'],
		size: [86, 110, 116, 122],
		quality1: ["vindtett", 'vanntett', "strikk"],
		price: "499",
		url: ['../images/pants/robust1.jpg', '../images/pants/robust2.jpg'],
		ingress: "Ungen kan rulle i søledammen i timesvis uten å bli våt.",
        description: "",
        id: 8,
		amount: 0 
    },
    {
		name: "Fulikuli",
		cathegory_main: "Bukser",
		cathegory_under: "Ullbukse",
		age: 2,
		color: ['red', 'gray'],
		size: [86, 110, 116, 122],
		quality1: ["varm"],
		price: "499",
		url: ['../images/pants/sisotinden_ull1.jpg', '../images/pants/sisotinden_ull2.jpg'],
		ingress: "Ungen kan rulle i søledammen i timesvis uten å bli våt.",
        description: "",
        id: 8,
		amount: 0 
    }
    ] 
;