const products = 
    [
	{
		name: "Robust",
		cathegory_main: "Jakker",
		cathegory_under: "Dunjakker",
		age: 1,
		color: ['green', 'red'],
		size: [86, 92, 104],
		quality1: "vannavstøtende",
		quality2: "vindtett",
		quality3: "",
		price: "255",
		url: ['../images/jackets/dalfonna1.jpg', '../images/jackets/dalfonna2.jpg', '../images/jackets/dalfonna3.jpg'],
		ingress: "Dette er en nydelig bukse som alle andre bukser",
        description: "",
        id: 1
        
	},
	{
		name: "Dirdalnes",
		cathegory_main: "Jakker",
		cathegory_under: "Skalljakker",
		age: 2,
		color: ['red'],
		size: [86, 92, 104, 110, 116, 122],
		quality1: "ull",
		quality2: "vanntett",
		quality3: "",
		price: "289",
		url: ['../images/jackets/dirdalnes_fleece1.jpg', '../images/jackets/dirdalnes_fleece2.jpg', '../images/jackets/dirdalnes_fleece3.jpg'],
		ingress: "Denne buksen er i deilig ull",
        description: "",
        id: 2
	},
	{
		name: "Moltehei",
		cathegory_main: "Jakker",
		cathegory_under: "Ullbukse",
		age: 3,
		color: ['red', 'blue'],
		size: [86, 110, 116, 122],
		quality1: "ull",
		quality2: "",
		quality3: "",
		price: "599",
		url: ['../images/jackets/Moltehei_softshell1.jpg', '../images/jackets/Moltehei_softshell2.jpg', '../images/jackets/Moltehei_softshell3.jpg'],
		ingress: "Denne jakken er i deilig ull",
        description: "",
        id: 3
	},
	{
		name: "Dalfonna vattert bukse",
		cathegory_main: "Bukser",
		cathegory_under: "Overtrekksbukse",
		age: 2,
		color: ['red', 'black'],
		size: [116, 122],
		quality1: "vindtett",
		quality2: "",
		quality3: "",
		price: "229",
		url: ['../images/pants/dalfonna_vattert1.jpg', '../images/pants/dalfonna_vattert2.jpg'],
		ingress: "Denne buksen er i deilig ull",
        description: "",
        id: 4
	},
	{
		name: "Sisotind",
		cathegory_main: "Bukser",
		cathegory_under: "Ullbukse",
		age: 2,
		color: ['red', 'gray'],
		size: [86, 116, 122],
		quality1: "vindtett",
		quality2: "vanntett",
		quality3: "strikk",
		price: "289",
		url: ['../images/jackets/dirdalnes_fleece3.jpg', '../images/jackets/dirdalnes_fleece1.jpg', '../images/jackets/dirdalnes_fleece2.jpg'],
		ingress: "Denne buksen er i deilig ull",
        description: "",
        id: 5
    },
    {
		name: "Fluppilupp",
		cathegory_main: "Jakker",
		cathegory_under: "Dunjakker",
		age: 2,
		color: ['red', 'gray'],
		size: [86, 110, 116, 122],
		quality1: "vindtett",
		quality2: "vanntett",
		quality3: "varm",
		price: "1299",
		url: ['../images/jackets/dirdalnes_fleece2.jpg', '../images/jackets/dirdalnes_fleece1.jpg', '../images/jackets/dirdalnes_fleece3.jpg'],
		ingress: "Dette er en fantastisk dunjakke",
        description: "",
        id: 6
    }
    ] 
;